version: 2
jobs:
  build:
    docker:
      - image: circleci/ubuntu-14.04-XXL-1327-3401d20
    steps:
      - checkout  
      - run: 
          name: Update Java
          command: sudo apt-get install
      - run: 
          name: Install Maven
          command: sudo apt-get install maven
      - run:
          name: Compile
          command: mvn clean compile test-compile
  test:
    docker:
      - image: circleci/ubuntu-14.04-XXL-1327-3401d20
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
